catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog: null

catalogs:
  build:
    tsdown: ^0.18.3
    vite: ^7.3.0
  cli:
    chokidar: 3.6.0
    citty: ^0.1.6
    colorette: ^2.0.20
    consola: ^3.4.2
  deps:
    automd: ^0.4.2
    bumpp: ^10.3.2
    c12: ^3.3.3
    defu: ^6.1.4
    fs-extra: ^11.3.3
    hookable: ^6.0.1
    jiti: ^2.6.1
    pathe: ^2.0.3
    perfect-debounce: ^2.0.0
    rimraf: ^6.1.2
    tinyglobby: ^0.2.15
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^6.7.3
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  playground:
    '@unocss/reset': ^66.5.10
    unocss: ^66.5.10
    vite-plugin-ejs: ^1.7.0
  test:
    '@vitest/coverage-v8': ^4.0.16
    tinyexec: ^1.0.2
    vitest: ^4.0.16
    vitest-package-exports: ^1.1.1
    yaml: ^2.8.2
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^25.0.3
    type-fest: ^5.3.1
