packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog: null

catalogs:
  build:
    tsdown: ^0.16.3
    vite: ^7.2.2
  cli:
    chokidar: 3.6.0
    citty: ^0.1.6
    colorette: ^2.0.20
    consola: ^3.4.2
  deps:
    automd: ^0.4.2
    bumpp: ^10.3.1
    c12: ^3.3.2
    defu: ^6.1.4
    fs-extra: ^11.3.2
    hookable: ^5.5.3
    jiti: ^2.6.1
    pathe: ^2.0.3
    perfect-debounce: ^2.0.0
    rimraf: ^6.1.0
    tinyglobby: ^0.2.15
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  playground:
    '@unocss/reset': ^66.5.6
    unocss: ^66.5.6
    vite-plugin-ejs: ^1.7.0
  test:
    '@vitest/coverage-v8': ^4.0.8
    vitest: ^4.0.8
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.10.1
    type-fest: ^5.2.0
