packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.2.1
  '@unocss/reset': ^66.4.2
  '@vitest/coverage-v8': ^3.2.4
  automd: ^0.4.0
  bumpp: ^10.2.3
  c12: ^3.2.0
  chokidar: ^3.6.0
  citty: ^0.1.6
  colorette: ^2.0.20
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^9.33.0
  fs-extra: ^11.3.1
  hookable: ^5.5.3
  jiti: ^2.5.1
  lint-staged: ^16.1.5
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.13.1
  tinyglobby: ^0.2.14
  type-fest: ^4.41.0
  typescript: ^5.9.2
  unbuild: ^3.6.0
  unocss: ^66.4.2
  vite: ^7.1.2
  vite-plugin-ejs: ^1.7.0
  vitest: ^3.2.4
