catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  build:
    tsdown: ^0.21.9
  deps:
    automd: ^0.4.3
    bumpp: ^11.0.1
    cac: ^7.0.0
    publint: ^0.3.18
  lint:
    '@antfu/eslint-config': ^8.2.0
    eslint: ^10.2.1
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
  test:
    '@vitest/coverage-v8': ^4.1.4
    tsnapi: ^0.3.2
    vitest: ^4.1.4
  types:
    '@types/node': ^25.6.0
    typescript: ^6.0.3
