packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.8.1
  '@types/node': ^22.13.9
  '@vitest/coverage-v8': ^3.0.8
  automd: ^0.4.0
  bumpp: ^10.0.3
  eslint: ^9.22.0
  jiti: ^2.4.2
  lint-staged: ^15.4.3
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  tinyglobby: ^0.2.12
  typescript: ^5.8.2
  unbuild: ^3.5.0
  vitest: ^3.0.8
  '@unocss/reset': ^65.4.3
  unocss: ^65.4.3
  vite: ^6.2.1
  vite-plugin-ejs: ^1.7.0
  '@types/fs-extra': ^11.0.4
  chokidar: ^3.6.0
  citty: ^0.1.6
  colorette: ^2.0.20
  consola: ^3.4.0
  fs-extra: ^11.3.0
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  c12: ^3.0.2
  defu: ^6.1.4
  hookable: ^5.5.3
  type-fest: ^4.37.0
